In [1]:
import pandas as pd

In [27]:
df = pd.read_csv('data/2014.csv')
df

,Team,Gms,TotÂ Pts,Pts/G,RushYds,RYds/G,PassYds,PYds/G,TotYds,Yds/G,year
0,Seattle SeahawksSeattle,16,254,15.9,1304,81.5,2970,185.6,4274,267.1,2014
1,Detroit LionsDetroit,16,282,17.6,1109,69.3,3706,231.6,4815,300.9,2014
2,Denver BroncosDenver,16,354,22.1,1276,79.8,3607,225.4,4883,305.2,2014
3,Buffalo BillsBuffalo,16,289,18.1,1703,106.4,3292,205.8,4995,312.2,2014
4,San Francisco 49ersSan Francisco,16,340,21.2,1612,100.8,3531,220.7,5143,321.4,2014
5,New York JetsNY Jets,16,401,25.1,1489,93.1,3746,234.1,5235,327.2,2014
6,Kansas City ChiefsKansas City,16,281,17.6,2036,127.2,3252,203.2,5288,330.5,2014
7,Baltimore RavensBaltimore,16,302,18.9,1412,88.2,3979,248.7,5391,336.9,2014
8,San Diego ChargersSan Diego,16,348,21.8,1986,124.1,3427,214.2,5413,338.3,2014
9,Carolina PanthersCarolina,16,374,23.4,1792,112.0,3645,227.8,5437,339.8,2014
10,Indianapolis ColtsIndianapolis,16,369,23.1,1814,113.4,3669,229.3,5483,342.7,2014
11,Miami DolphinsMiami,16,373,23.3,1937,121.1,3557,222.3,5494,343.4,2014
12,New England PatriotsNew England,16,313,19.6,1669,104.3,3837,239.8,5506,344.1,2014
13,Minnesota VikingsMinnesota,16,343,21.4,1943,121.4,3572,223.2,5515,344.7,2014
14,Green Bay PackersGreen Bay,16,348,21.8,1919,119.9,3623,226.4,5542,346.4,2014
15,Houston TexansHouston,16,307,19.2,1681,105.1,3890,243.1,5571,348.2,2014
16,St. Louis RamsSt. Louis,16,354,22.1,1765,110.3,3861,241.3,5626,351.6,2014
17,Pittsburgh SteelersPittsburgh,16,368,23.0,1605,100.3,4049,253.1,5654,353.4,2014
18,Dallas CowboysDallas,16,352,22.0,1650,103.1,4031,251.9,5681,355.1,2014
19,Washington RedskinsWashington,16,438,27.4,1722,107.6,3990,249.4,5712,357.0,2014
20,Oakland RaidersOakland,16,452,28.2,1911,119.4,3810,238.1,5721,357.6,2014
21,Cincinnati BengalsCincinnati,16,344,21.5,1861,116.3,3888,243.0,5749,359.3,2014
22,Cleveland BrownsCleveland,16,337,21.1,2265,141.6,3592,224.5,5857,366.1,2014
23,Arizona CardinalsArizona,16,299,18.7,1739,108.7,4152,259.5,5891,368.2,2014
24,Tampa Bay BuccaneersTampa Bay,16,410,25.6,1819,113.7,4084,255.2,5903,368.9,2014
25,Jacksonville JaguarsJacksonville,16,412,25.8,2033,127.1,3899,243.7,5932,370.8,2014
26,Tennessee TitansTennessee,16,438,27.4,2195,137.2,3773,235.8,5968,373.0,2014
27,Philadelphia EaglesPhiladelphia,16,400,25.0,1771,110.7,4238,264.9,6009,375.6,2014
28,New York GiantsNY Giants,16,400,25.0,2162,135.1,3850,240.6,6012,375.8,2014
29,Chicago BearsChicago,16,442,27.6,1803,112.7,4230,264.4,6033,377.1,2014
30,New Orleans SaintsNew Orleans,16,424,26.5,2125,132.8,4019,251.2,6144,384.0,2014
31,Atlanta FalconsAtlanta,16,417,26.1,1894,118.4,4478,279.9,6372,398.2,2014

In [33]:
playoff = ['True', 'True', 'True', 'False', 'False', 'False', 'False', 'True', 'False', 'True', 'True', 'False', 'True', 'False', 'True', 'False', 'False', 'True', 'True', 'False', 'False', 'True', 'False', 'True', 'False', 'False', 'False', 'False', 'False', 'False', 'False', 'False']

In [34]:
df['Playoff'] = playoff
df
# len(playoff), playoff.count('True'), playoff.count('False')

,Team,Gms,TotÂ Pts,Pts/G,RushYds,RYds/G,PassYds,PYds/G,TotYds,Yds/G,year,Playoff
0,Seattle SeahawksSeattle,16,254,15.9,1304,81.5,2970,185.6,4274,267.1,2014,True
1,Detroit LionsDetroit,16,282,17.6,1109,69.3,3706,231.6,4815,300.9,2014,True
2,Denver BroncosDenver,16,354,22.1,1276,79.8,3607,225.4,4883,305.2,2014,True
3,Buffalo BillsBuffalo,16,289,18.1,1703,106.4,3292,205.8,4995,312.2,2014,False
4,San Francisco 49ersSan Francisco,16,340,21.2,1612,100.8,3531,220.7,5143,321.4,2014,False
5,New York JetsNY Jets,16,401,25.1,1489,93.1,3746,234.1,5235,327.2,2014,False
6,Kansas City ChiefsKansas City,16,281,17.6,2036,127.2,3252,203.2,5288,330.5,2014,False
7,Baltimore RavensBaltimore,16,302,18.9,1412,88.2,3979,248.7,5391,336.9,2014,True
8,San Diego ChargersSan Diego,16,348,21.8,1986,124.1,3427,214.2,5413,338.3,2014,False
9,Carolina PanthersCarolina,16,374,23.4,1792,112.0,3645,227.8,5437,339.8,2014,True
10,Indianapolis ColtsIndianapolis,16,369,23.1,1814,113.4,3669,229.3,5483,342.7,2014,True
11,Miami DolphinsMiami,16,373,23.3,1937,121.1,3557,222.3,5494,343.4,2014,False
12,New England PatriotsNew England,16,313,19.6,1669,104.3,3837,239.8,5506,344.1,2014,True
13,Minnesota VikingsMinnesota,16,343,21.4,1943,121.4,3572,223.2,5515,344.7,2014,False
14,Green Bay PackersGreen Bay,16,348,21.8,1919,119.9,3623,226.4,5542,346.4,2014,True
15,Houston TexansHouston,16,307,19.2,1681,105.1,3890,243.1,5571,348.2,2014,False
16,St. Louis RamsSt. Louis,16,354,22.1,1765,110.3,3861,241.3,5626,351.6,2014,False
17,Pittsburgh SteelersPittsburgh,16,368,23.0,1605,100.3,4049,253.1,5654,353.4,2014,True
18,Dallas CowboysDallas,16,352,22.0,1650,103.1,4031,251.9,5681,355.1,2014,True
19,Washington RedskinsWashington,16,438,27.4,1722,107.6,3990,249.4,5712,357.0,2014,False
20,Oakland RaidersOakland,16,452,28.2,1911,119.4,3810,238.1,5721,357.6,2014,False
21,Cincinnati BengalsCincinnati,16,344,21.5,1861,116.3,3888,243.0,5749,359.3,2014,True
22,Cleveland BrownsCleveland,16,337,21.1,2265,141.6,3592,224.5,5857,366.1,2014,False
23,Arizona CardinalsArizona,16,299,18.7,1739,108.7,4152,259.5,5891,368.2,2014,True
24,Tampa Bay BuccaneersTampa Bay,16,410,25.6,1819,113.7,4084,255.2,5903,368.9,2014,False
25,Jacksonville JaguarsJacksonville,16,412,25.8,2033,127.1,3899,243.7,5932,370.8,2014,False
26,Tennessee TitansTennessee,16,438,27.4,2195,137.2,3773,235.8,5968,373.0,2014,False
27,Philadelphia EaglesPhiladelphia,16,400,25.0,1771,110.7,4238,264.9,6009,375.6,2014,False
28,New York GiantsNY Giants,16,400,25.0,2162,135.1,3850,240.6,6012,375.8,2014,False
29,Chicago BearsChicago,16,442,27.6,1803,112.7,4230,264.4,6033,377.1,2014,False
30,New Orleans SaintsNew Orleans,16,424,26.5,2125,132.8,4019,251.2,6144,384.0,2014,False
31,Atlanta FalconsAtlanta,16,417,26.1,1894,118.4,4478,279.9,6372,398.2,2014,False

In [26]:
df.to_csv('data/2014_Update.csv', index=False)